

spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost:9092/~/test
#    username: sa
#    password: 1234
    url: jdbc:oracle:thin:@localhost:1521/xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: System
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 60000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariCorePool
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: select * from information_schema.tables limit 1
  devtools:
    restart:
      enabled: false
  thymeleaf:
    cache: false

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 8080
