
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: System
    password: 1234
    hikari:
      data-source-class-name: oracle.jdbc.OracleDriver
      connection-test-query: SELECT 1
#      maximum-pool-size: 8
#      connection-timeout: 5000
#      connection-init-sql: SELECT 1
#      validation-timeout: 2000
#      minimum-idle: 10
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      leakDetectionThreshold: 60000
#      auto-commit: true

#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: none

